### ISSUE TITLE
Second round of wording and grammar changes (IoT, not FAQ)

### ISSUE THREAD

**Issue by hnichols9560** [mit-cml/iot-website-source#109]
Hedge format: 

- [x] Your friendly checkbox! URL
Old wording
New wording or question

General Questions

- [ ] http://iot.appinventor.mit.edu/#/arduino101/arduino101intro	
The Arduino 101 is a version of the popular Arduino platform based on the Intel® Curie™ chipset. It has the same form factor as many other Arduino but supports built-in Bluetooth® low energy.	What if I don't know what an Arduino is or what it does?

- [ ] http://iot.appinventor.mit.edu/#/bluetoothle/bluetoothleintro	
Bluetooth Low Energy, also referred to as Bluetooth LE or simply BLE, is a new protocol similar to classic Bluetooth except that it is designed to consume less power while maintaining comparable functionality. 	
What if I don't know what a Bluetooth is?  Can we refer to it as a connection protocol or something?

- [x] http://iot.appinventor.mit.edu/#/help/intro	
Next steps:	
"Next steps" and the line above it should be removed. The text on this page should begin with, "Now that you are up and running...."

- [ ] http://iot.appinventor.mit.edu/#/getstarted/intro	
"example not yet read" 
Please remove this text.

- [x] http://iot.appinventor.mit.edu/#/bluetoothle/bluetoothleintro
BytesWritten – Event for BytesWritten 
What does this mean?

Wording Changes

- [x] http://iot.appinventor.mit.edu/#/	
Make apps that connect to the Internet of Things with MIT App Inventor!	
Make apps for the Internet of Things with MIT App Inventor!

- [x] http://iot.appinventor.mit.edu/#/getstarted/intro	
You may already know how to build mobile apps with MIT App Inventor, but if you are new to this way of building apps we suggest you please click here to become familiar with some basic functions in MIT App Inventor.	
You may already know how to build mobile apps with MIT App Inventor, but if you are new to this system, please click here to become familiar with some basic functions in MIT App Inventor.

- [x] http://iot.appinventor.mit.edu/#/teachers/intro	
You may already know that MIT App Inventor lets you help your students create original mobile apps that can make real-world differences to themselves and their communities.	
You may already know that MIT App Inventor helps your students create original mobile apps that can make real-world differences for themselves and their communities.

- [x] http://iot.appinventor.mit.edu/#/teachers/intro	
App Inventor IoT extends the reach of mobile apps to sensors, actuators, robots and to an expanding universe of connected devices.	
App Inventor IoT extends the reach of mobile apps to sensors, actuators, robots, and an expanding universe of connected devices.

- [x] http://iot.appinventor.mit.edu/#/teachers/intro	
The biggest difference between ordinary MIT App Inventor apps and MIT App Inventor IoT apps is that IoT apps communicate with external devices through IoT devices controllers	
The biggest difference between ordinary MIT App Inventor apps and MIT App Inventor IoT apps is that IoT apps communicate with external devices using IoT device controllers.

- [x] http://iot.appinventor.mit.edu/#/teachers/intro	
Your students can build apps with all kinds of sensors (like sensors for temperature, moisture, noise, light, color, or motion) and other devices (like buttons and switches and relays) connected to a controller.	
Your students can build apps with all kinds of sensors (like sensors for temperature, moisture, noise, light, color, or motion) and other devices (like buttons, switches, and relays) connected to a controller.

- [x] http://iot.appinventor.mit.edu/#/students/examples	
This app gives an individual more power over their environment, rather than having to rely on others.	
This app gives individuals self-reliance, and control over their environment.

- [x] http://iot.appinventor.mit.edu/#/teachers/examples	
This allows individuals who are confined to bed rest to change the lighting independently without needing to request caregiver assistance.	
This allows individuals who are confined to bed rest to change the lighting independently, without caregiver assistance.

- [x] http://iot.appinventor.mit.edu/#/students/intro	
Now, with the Internet of Things extension to App Inventor (MIT App Inventor IoT) your apps can connect to physical and digital objects all around you!	
Now, with the Internet of Things extension to App Inventor (MIT App Inventor IoT), your apps can connect to physical and digital objects all around you!

- [x] http://iot.appinventor.mit.edu/#/students/intro	
You can use sensors to capture a wealth of data, including temperature, sound, light, color, moisture, motion, touch, heart rate, and many more, with support for new sensors appearing daily.	
You can use sensors to capture a wealth of data, including temperature, sound, light, color, moisture, motion, touch, heart rate, and much more, with support for new sensors appearing daily.

- [x] http://iot.appinventor.mit.edu/#/students/intro	
You can combine controls and sensors with all the other features of your App Inventor apps like speech recognition, databases and communication.	
You can combine controls and sensors with all the other features of your App Inventor apps, like speech recognition, databases, and communication.

- [x] http://iot.appinventor.mit.edu/#/makers/intro	
One is mobile computing: we now carry around with us computers of tremendous power that can link over the Internet to vast resources of data and computation.	
One is mobile computing: we now carry with us computers of tremendous power that linked to vast resources of data and computation.

- [x] http://iot.appinventor.mit.edu/#/help/intro	
Find all the help you need to get started in teaching, learning and using IoT with MIT App Inventor.	
Find all the help you need to get started with teaching, learning and using IoT with MIT App Inventor.

- [x] http://iot.appinventor.mit.edu/#/help/intro	
We also have a number of resources available to help you with building your IoT apps with MIT App Inventor.	
We have a number of resources to help you build IoT apps with MIT App Inventor.

- [x] http://iot.appinventor.mit.edu/#/devices/devicesintro	
Before building your IoT creations you need to set up your environment.	
Before building for IoT, you need to set up your environment.

- [x] http://iot.appinventor.mit.edu/#/devices/devicesintro	
Next, we need to learn how to build an App Inventor app that can connect to our Arduino.	
Next, you need to learn how to build an App Inventor app that can connect to our Arduino.

- [x] http://iot.appinventor.mit.edu/#/devices/devicesintro	
At present, we use Bluetooth to connect to our IoT Devices (we are working on WiFi).	
At present, we use Bluetooth to connect to our IoT Devices (Wifi connection coming soon).

- [x] http://iot.appinventor.mit.edu/#/devices/devicesintro	
Building a basic app that can connect via bluetooth is easy.	
Building basic apps that connect via Bluetooth is easy.

- [x] http://iot.appinventor.mit.edu/#/devices/devicesintro	
These pages contain all the detailed documentation on how to use these devices with App Inventor. 	
These pages contain detailed documentation on how to use these devices with App Inventor.

- [x] http://iot.appinventor.mit.edu/#/devices/devicesintro	
These pages will help you discover all the features available, and how to use them.	
These pages will help you discover available features, and how to use them.  OR These pages will help you discover all the features your IoT devices have to offer, and how to use them.

- [x] http://iot.appinventor.mit.edu/#/bluetoothle/bluetoothleintro	
BatteryValue – Return the battery level.	
BatteryValue – Returns the battery level.

- [x] http://iot.appinventor.mit.edu/#/bluetoothle/bluetoothleintro	
ConnectedDeviceRssi – Return the RSSI (Received Signal Strength Indicator) of connected device.	
ConnectedDeviceRssi – Returns the RSSI (Received Signal Strength Indicator) of connected device.

- [x] http://iot.appinventor.mit.edu/#/bluetoothle/bluetoothleintro	
DeviceList – Return a sorted list of BluetoothLE devices as a String.
DeviceList – Returns a sorted list of BluetoothLE devices as a String.

- [x] http://iot.appinventor.mit.edu/#/bluetoothle/bluetoothleintro
IsDeviceConnected – Return true if a BluetoothLE device is connected; Otherwise, return false.
IsDeviceConnected – Returns true if a BluetoothLE device is connected; Otherwise, return false.

- [x] http://iot.appinventor.mit.edu/#/bluetoothle/bluetoothleintro
TxPower – Return the Tx power.
TxPower – Returns the Tx power.

- [x] http://iot.appinventor.mit.edu/#/bluetoothle/bluetoothleintro
CharacteristicByIndex – Return Unique ID of selected characteristic with index. Index specified by list of supported characteristics for a connected device, starting from 1.
CharacteristicByIndex – Returns Unique ID of selected characteristic with index. Index specified by list of supported characteristics for a connected device, starting from 1.

- [x] http://iot.appinventor.mit.edu/#/bluetoothle/bluetoothleintro
Connect – Connect to a BluetoothLE device with index. Index specifies the position in BluetoothLE device list, starting from 1.
Connect – Connects to a BluetoothLE device with index. Index specifies the position in BluetoothLE device list, starting from 1.

- [x] http://iot.appinventor.mit.edu/#/bluetoothle/bluetoothleintro
ConnectWithAddress – Connect to BluetoothLE device with address. Address specifies bluetooth address of the BluetoothLE device.
ConnectWithAddress – Connects to BluetoothLE device with address. Address specifies bluetooth address of the BluetoothLE device.

- [x] http://iot.appinventor.mit.edu/#/bluetoothle/bluetoothleintro
Disconnect – Disconnect from the currently connected BluetoothLE device if a device is connected.
Disconnect – Disconnects from the currently connected BluetoothLE device if a device is connected.

- [x] http://iot.appinventor.mit.edu/#/bluetoothle/bluetoothleintro
DisconnectWithAddress – Disconnect from connected BluetoothLE device with address. 
DisconnectWithAddress – Disconnects from connected BluetoothLE device with address. 

- [x] http://iot.appinventor.mit.edu/#/bluetoothle/bluetoothleintro
FoundDeviceAddress – Get the address of found device with index. Index specifies the position in BluetoothLE device list, starting from 1.
FoundDeviceAddress – Gets the address of found device with index. Index specifies the position in BluetoothLE device list, starting from 1.

- [x] http://iot.appinventor.mit.edu/#/bluetoothle/bluetoothleintro
FoundDeviceName – Get the name of found device with index. Index specifies the position in BluetoothLE device list, starting from 1.
FoundDeviceName – Gets the name of found device with index. Index specifies the position in BluetoothLE device list, starting from 1.

- [x] http://iot.appinventor.mit.edu/#/bluetoothle/bluetoothleintro
FoundDeviceRssi – Get the RSSI (Received Signal Strength Indicator) of found device with index. Index specifies the position in BluetoothLE device list, starting from 1.
FoundDeviceRssi – Gets the RSSI (Received Signal Strength Indicator) of found device with index. Index specifies the position in BluetoothLE device list, starting from 1.

- [x] http://iot.appinventor.mit.edu/#/bluetoothle/bluetoothleintro
GetCharacteristicsForService – Return list of supported characteristics for the given service. The list will contain (UUID, name) pairs for each characteristic provided by the given service UUID.
GetCharacteristicsForService – Returns list of supported characteristics for the given service. The list will contain (UUID, name) pairs for each characteristic provided by the given service UUID.

- [x] http://iot.appinventor.mit.edu/#/bluetoothle/bluetoothleintro
ReadBytes – Read one or more 8-bit integer values from a connected BluetoothLE device. Service Unique ID and Characteristic Unique ID are required.
ReadBytes – Reads one or more 8-bit integer values from a connected BluetoothLE device. Service Unique ID and Characteristic Unique ID are required.

- [x] http://iot.appinventor.mit.edu/#/bluetoothle/bluetoothleintro
ReadFloats – Read one or more floating point values from a connected Bluetooth device.
ReadFloats – Reads one or more floating point values from a connected Bluetooth device.

- [x] http://iot.appinventor.mit.edu/#/bluetoothle/bluetoothleintro
ReadIntegers – Read one or more 32-bit integer values from a connected BluetoothLE device.
ReadIntegers – Reads one or more 32-bit integer values from a connected BluetoothLE device.

- [x] http://iot.appinventor.mit.edu/#/bluetoothle/bluetoothleintro
ReadShorts – Read one or more 16-bit integer values from a connected BluetoothLE device. Service Unique ID and Characteristic Unique ID are required.
ReadIntegers – Reads one or more 32-bit integer values from a connected BluetoothLE device.

- [x] http://iot.appinventor.mit.edu/#/bluetoothle/bluetoothleintro
ReadStrings – Read one or more strings from a connected Bluetooth device.
ReadStrings – Reads one or more strings from a connected Bluetooth device.

- [x] http://iot.appinventor.mit.edu/#/bluetoothle/bluetoothleintro
RegisterForBytes – Register to receive updates when one or more 16-bit integer values from a connected BluetoothLE change. 
RegisterForBytes – Registers to receive updates when one or more 16-bit integer values from a connected BluetoothLE change. 

- [x] http://iot.appinventor.mit.edu/#/bluetoothle/bluetoothleintro
RegisterForFloats – Register to receive updates when one or more floating point values from a connected Bluetooth device change.
RegisterForFloats – Registers to receive updates when one or more floating point values from a connected Bluetooth device change.

- [x] http://iot.appinventor.mit.edu/#/bluetoothle/bluetoothleintro
RegisterForFloats – Register to receive updates when one or more floating point values from a connected Bluetooth device change.
RegisterForFloats – Registers to receive updates when one or more floating point values from a connected Bluetooth device change.

- [x] http://iot.appinventor.mit.edu/#/bluetoothle/bluetoothleintro
RegisterForShorts – Register to receive updates when one or more 16-bit integer values from a connected BluetoothLE change. Service Unique ID and Characteristic Unique IDare required.
RegisterForShorts – Registers to receive updates when one or more 16-bit integer values from a connected BluetoothLE change. Service Unique ID and Characteristic Unique ID are required.

- [x] http://iot.appinventor.mit.edu/#/bluetoothle/bluetoothleintro
RegisterForStrings – Register to receive updates when one or more string values froma connected Bluetooth device change.
RegisterForStrings – Registers to receive updates when one or more string values froma connected Bluetooth device change.

- [x] http://iot.appinventor.mit.edu/#/bluetoothle/bluetoothleintro
ServiceByIndex – Return Unique ID of selected service with index. Index specified by list of supported services for a connected device, starting from 1.
ServiceByIndex – Returns Unique ID of selected service with index. Index specified by list of supported services for a connected device, starting from 1.

- [x] http://iot.appinventor.mit.edu/#/bluetoothle/bluetoothleintro
StartAdvertising – Create and publish a Bluetooth LE advertisement.
StartAdvertising – Creates and publishes a Bluetooth LE advertisement. 

- [x] http://iot.appinventor.mit.edu/#/bluetoothle/bluetoothleintro
StartScanning – Start Scanning for BluetoothLE devices.
StartScanning – Starts Scanning for BluetoothLE devices.

- [x] http://iot.appinventor.mit.edu/#/bluetoothle/bluetoothleintro
StopAdvertising – Stop Bluetooth LE Advertising
StopAdvertising – Stops Bluetooth LE Advertising

- [x] http://iot.appinventor.mit.edu/#/bluetoothle/bluetoothleintro
StopScanning – Stop Scanning for BluetoothLE devices.
StopScanning – Stops Scanning for BluetoothLE devices.

- [x] http://iot.appinventor.mit.edu/#/bluetoothle/bluetoothleintro
SupportedCharacteristics – Return list of supported characteristics for connected device as a String
SupportedCharacteristics – Returns list of supported characteristics for connected device as a String

- [x] http://iot.appinventor.mit.edu/#/bluetoothle/bluetoothleintro
SupportedServices – Return list of supported services for connected device as a String
SupportedServices – Returns list of supported services for connected device as a String

- [x] http://iot.appinventor.mit.edu/#/bluetoothle/bluetoothleintro
UnregisterForValues – Unregister for updates for the given service and characteristic.
UnregisterForValues – Unregisters for updates for the given service and characteristic.

- [x] http://iot.appinventor.mit.edu/#/bluetoothle/bluetoothleintro
WriteBytes – Write one or more 8-bit integer values to a connected BluetoothLE device. 
WriteBytes – Writes one or more 8-bit integer values to a connected BluetoothLE device. 

- [x] http://iot.appinventor.mit.edu/#/bluetoothle/bluetoothleintro
WriteBytesWithResponse – Write one or more 8-bit integer values to a connected BluetoothLE device and wait for an acknowledgement via the ByteValuesWritten event.
WriteBytesWithResponse – Writes one or more 8-bit integer values to a connected BluetoothLE device and wait for an acknowledgement via the ByteValuesWritten event.

- [x] http://iot.appinventor.mit.edu/#/bluetoothle/bluetoothleintro
WriteFloats – Write one or more floating point values to a connected BluetoothLE device.
WriteFloats – Writes one or more floating point values to a connected BluetoothLE device.

- [x] http://iot.appinventor.mit.edu/#/bluetoothle/bluetoothleintro
WriteFloatsWithResponse – Write one or more 8-bit integer values to a connected BluetoothLE device and wait for an acknowledgement via the FloatValuesWritten event.
WriteFloatsWithResponse – Writes one or more 8-bit integer values to a connected BluetoothLE device and wait for an acknowledgement via the FloatValuesWritten event.

- [x] http://iot.appinventor.mit.edu/#/bluetoothle/bluetoothleintro
WriteIntegers – Write one or more 32-bit integer values to a connected BluetoothLE device. 
WriteIntegers – Writes one or more 32-bit integer values to a connected BluetoothLE device. 

- [x] http://iot.appinventor.mit.edu/#/bluetoothle/bluetoothleintro
WriteIntegersWithResponse – Write one or more 32-bit integer values to a connected BluetoothLE device and wait for an acknowledgement via the IntegerValuesWritten event. 
WriteIntegersWithResponse – Writes one or more 32-bit integer values to a connected BluetoothLE device and wait for an acknowledgement via the IntegerValuesWritten event. 

- [x] http://iot.appinventor.mit.edu/#/bluetoothle/bluetoothleintro
WriteShorts – Write one or more 16-bit integer values to a connected BluetoothLE device. 
WriteShorts – Writes one or more 16-bit integer values to a connected BluetoothLE device. 

- [x] http://iot.appinventor.mit.edu/#/bluetoothle/bluetoothleintro
WriteShortsWithResponse – Write one or more 16-bit integer values to a connected BluetoothLE device and wait for an acknowledgement via the ShortValuesWritten event.Service Unique ID and Characteristic Unique ID are required.
WriteShortsWithResponse – Writes one or more 16-bit integer values to a connected BluetoothLE device and wait for an acknowledgement via the ShortValuesWritten event. Service Unique ID and Characteristic Unique ID are required.

- [x] http://iot.appinventor.mit.edu/#/bluetoothle/bluetoothleintro
WriteStrings – Write one or more strings to a connected BluetoothLE device. 
WriteStrings – Writes one or more strings to a connected BluetoothLE device. 

- [x] http://iot.appinventor.mit.edu/#/bluetoothle/bluetoothleintro
WriteStringsWithResponse – Write one or more strings to a connected BluetoothLE device and wait for an acknowledgement. 
WriteStringsWithResponse – Writes one or more strings to a connected BluetoothLE device and wait for an acknowledgement. 

- [x] http://iot.appinventor.mit.edu/#/bluetoothle/bluetoothleintro
BytesReceived – Trigger event when one or more byte values from a connected BluetoothLE device are received.
BytesReceived – Triggers event when one or more byte values from a connected BluetoothLE device are received.

- [x] http://iot.appinventor.mit.edu/#/bluetoothle/bluetoothleintro
Connected – Trigger event when a BluetoothLE device is connected.
Connected – Triggers event when a BluetoothLE device is connected.

- [x] http://iot.appinventor.mit.edu/#/bluetoothle/bluetoothleintro
DeviceFound – Trigger event when a new BluetoothLE device is found.
DeviceFound – Triggers event when a new BluetoothLE device is found.

- [x] http://iot.appinventor.mit.edu/#/bluetoothle/bluetoothleintro
FloatsReceived – Trigger event when one or more floating point values from a BluetoothLE device are received.
FloatsReceived – Triggers event when one or more floating point values from a BluetoothLE device are received.

- [x] http://iot.appinventor.mit.edu/#/bluetoothle/bluetoothleintro
IntegersReceived – Trigger event when one or more integer values from a connected BluetoothLE device are received.
IntegersReceived – Triggers event when one or more integer values from a connected BluetoothLE device are received.

- [x] http://iot.appinventor.mit.edu/#/bluetoothle/bluetoothleintro
RssiChanged – Trigger event when RSSI (Received Signal Strength Indicator) of found BluetoothLE device changes
RssiChanged – Triggers event when RSSI (Received Signal Strength Indicator) of found BluetoothLE device changes

- [x] http://iot.appinventor.mit.edu/#/bluetoothle/bluetoothleintro
ShortsReceived – Trigger event when one or more short values from a connected BluetoothLE device are received.
ShortsReceived – Triggers event when one or more short values from a connected BluetoothLE device are received.

- [x] http://iot.appinventor.mit.edu/#/bluetoothle/bluetoothleintro
StringsReceived – Trigger event when one or more string values from a connected BluetoothLE device a received.
StringsReceived – Triggers event when one or more string values from a connected BluetoothLE device a received.

**Comment by marksherman** [comment]
I suspect the API descriptions may be auto-generated from the source code. @ewpatton is this worth changing here?

**Comment by ewpatton** [comment]
Closed by #137
