### ISSUE TITLE
Mobile. Small screens.

### ISSUE THREAD

**Issue by marksherman** [mit-cml/iot-website-source#133]
Do it right with Flex. Make sure nav works right on small screens. Invent the media query mechanism as necessary.

**Comment by ewpatton** [comment]
Is there any reason to not just hide the top navbar once the screen gets small enough? At some point at any readable font the text will not fit on a single horizontal line.

**Comment by ewpatton** [comment]
Determine whether PR #153 addresses this issue.

**Comment by marksherman** [comment]
Fixed by #153 , and others
