### ISSUE TITLE
FAQ Addition

### ISSUE THREAD

**Issue by farxinu** [mit-cml/iot-website-source#141]
Sorry for ANOTHER one of these. 

FAQ says: 
> When I run the Arduino sketch, I get ".hh: No Such file or directory"
> 
> This error, referring to Accelerometer.hh or another file that ends in .hh, probably means that your Arduino IDE is out of date. Please download the latest Arduino IDE and try again. At the time of writing this, the current version is 1.8.3.
> 
> The sensors/outputs on my Arduino are behaving oddly/are very jittery.
> 
> Some hardware require 5V input rather than 3.3V. If you are using the Grove shield, make sure you have the Arduino's power input set to 5V. The RGB LCD, for example, requires 5V. Without it, there is not enough power to drive the liquid crystal display and characters will not appear.
> 
> When I connect to the Arduino over Bluetooth, the app crashes.
> 
> Check that you have the right pin set in the property tab for the device in the designer.

This is great, but for instance, with the proximity sensor, if you don't have enough power OR if you're on the wrong pin, you get zero readings. The symptoms are the same. This should be addressed in the FAQ in some way (or on the Proximity Sensor page).
Also, there are more reasons why the app might crash. For instance, the exact same code crashes an LG tablet when connected as a companion but not a Google Pixel companion. Same code, same app version, same everything. We don't have an exact diagnosis for that issue yet (Mike's looking into it). If we get an update, we'll let you know and update this issue.

**Comment by halatmit** [comment]
Thanks for catching this.   We can expect more of this kind of issue.


== Hal

Hal Abelson
hal@mit.edu
Prof. of Comp. Sci. and Eng.
MIT Dept. of Elec. Eng. and Comp. Sci.


On Thu, Jun 15, 2017 at 12:11 PM, Farzeen Harunani <notifications@github.com
