### ISSUE TITLE
font contradiction issue in home page and home page side navigation menu  

### ISSUE THREAD

**Issue by BhavyaMPatel** [mit-cml/iot-website-source#216]
###

**Comment by draunger** [comment]
@BhavyaMPatel I want to do this issue

**Comment by BhavyaMPatel** [comment]
@draunger I am not moderatore of this repo you can ask @alltom @justinabrahms @garth 
thank u !

**Comment by draunger** [comment]
@alltom can I work on this

**Comment by alltom** [comment]
Did you all mean to tag someone else with an "al" name like "alitaheri"? I don't know what this repo is.

**Comment by ewpatton** [comment]
@draunger The website built from these sources has been deprecated, so we are not taking any new fixes at this time.
