### ISSUE TITLE
add "Contact Us" to side nav

### ISSUE THREAD

**Issue by marksherman** [mit-cml/iot-website-source#30]
It can also stay in the footer, but testing showed nobody found it in the footer when directed. Needs to be in left-side nav, at bottom. Possibly under "Help".
![6-2 contact us](https://user-images.githubusercontent.com/2035149/26842464-ecdb83f2-4aba-11e7-8cd1-a51ee1afaa1d.png)

**Comment by farxinu** [comment]
Is this a mailto link or a web form...?

**Comment by marksherman** [comment]
it is a link to the existing Contact Us form on the central app inventor site.

**Comment by farxinu** [comment]
Ok we should be careful then. We don't want the "contact us" form to be used to sending us their issues. Let's make sure that's made clear in the FAQ.

**Comment by afmckinney** [comment]
This is done in my latest pull request
