### ISSUE TITLE
Break "learn more" into big buttons on home page

### ISSUE THREAD

**Issue by marksherman** [mit-cml/iot-website-source#33]
Current "Learn more" is replaced with button "Learn more about IoT". Another button next to it "Learn more about App Inventor" that goes to the explore site, or other reasonable page to learn more about app inventor.
![home buttons](https://user-images.githubusercontent.com/2035149/26842712-c92fcb56-4abb-11e7-8f1a-0dc596866f8d.png)

**Comment by afmckinney** [comment]
I assume you mean MIT App Inventor not MIT Apple Inventor. ;-)

**Comment by marksherman** [comment]
...are we not inventing apples?

**Comment by marksherman** [comment]
I really thought we had something here.
