### ISSUE TITLE
Help Page

### ISSUE THREAD

**Issue by farxinu** [mit-cml/iot-website-source#41]
The "Help" landing page shows Forums, FAQ, and More to Discover, but none of these are hyperlinks, and don't correlate to the three links actually under Help (Devices, FAQ, Forum).

**Comment by marksherman** [comment]
This is a major rewrite, and I think someone was working on it? Marsha, maybe. Now we have a place to organize that work, right here.

**Comment by marksherman** [comment]
I'd say for #52 satisfies the concerns here. If others disagree, we can re-open and have more conversation, but for this version, I'd call it done. We can create a new issue for a full content rewrite.
