### ISSUE TITLE
Sitewide Wording Suggestions

### ISSUE THREAD

**Issue by hnichols9560** [mit-cml/iot-website-source#46]
As promised, here are the sitewide wording suggestions.  They have been reviewed by Karen and Hal.
Thanks so much!

Hedge

- [x] http://iot.appinventor.mit.edu/#/	
“You can create apps for the Internet of Things with MIT App Inventor!” 	
Please change to: "Make apps that connect to the Internet of Things with MIT App Inventor!”	

- [x] http://iot.appinventor.mit.edu/#/	
“MIT App Inventor lets people around the world build mobile apps that can make a difference in their families, schools, and communities—even if they've never programmed before.”	
Please replace with: “MIT App Inventor helps people around the world build mobile apps that can make a difference for their families, schools, and communities -- even if they've never programmed before.”																						
- [x] http://iot.appinventor.mit.edu/#/	
“Developing IoT applications using MIT App Inventor works the same way as developing any other mobile apps with App Inventor, but now your apps can interact with objects all around you.”	
Please replace with: "You can develop IoT applications the same way you develop any other MIT App Inventor mobile apps, but now you can use the apps to interact with objects all around you."	
																				
- [x] http://iot.appinventor.mit.edu/#/LearnMore	
“This first App Inventor IoT release includes software that operates with the Arduino 101 and the BBC Micro:Bit, and MIT will be adding more interfaces soon.”	
Please replace with: “This first App Inventor IoT release works with the Arduino 101 and the BBC Micro:Bit, and we will be adding more devices soon!”	
																					
- [x] http://iot.appinventor.mit.edu/#/LearnMore	
“The Internet of Things (IoT) refers to the connection of everyday objects to the Internet and to each other, leading to smarter devices and opening up an entire universe of new applications and opportunities.”	
Please replace with: "The Internet of Things (IoT) refers to interfaces between everyday objects and the Internet, opening up a universe of new applications, smarter devices, and wider opportunities.”	
																					
- [x] http://iot.appinventor.mit.edu/#/LearnMore	
“Developing IoT applications works the same way as with other MIT App Inventor mobile apps, but now you can program devices, sensor, appliances, instruments. robots—anything that can be connected.”	
"You can develop IoT applications the same way you develop any other MIT App Inventor mobile apps.  Now you can program devices, sensors, appliances, instruments, robots -- anything that can be connected."	
																				
- [x] http://iot.appinventor.mit.edu/#/teachers/intro	“They can use App Inventor to program the controller to trigger connected devices (like turning on lights, playing sounds, or moving motors), or signal events to other devices, including smartphones running your students' App Inventor apps.”	“Using App Inventor, they can program controllers to trigger connected devices to activate sensors, turn on lights, play sounds, move motors, and more! Students can even control the devices from their smartphones!”	
																					
- [x] http://iot.appinventor.mit.edu/#/teachers/examples	
“Description: The home lighting automation system allows a young people who is confined to bed rest to turn on and off the lights in the room, so they don’t have to ask their parents or friends for help. The MIT App Inventor IoT app allows the person to communicate with the lights using Arduino with Bluetooth and a relay.”	
Please replace with: “Description: Turn the lights on and off without leaving your bed with a home lighting automation system. This allows individuals who are confined to bed rest to change the lighting independently without needing to request caregiver assistance.”	
																					
- [x] http://iot.appinventor.mit.edu/#/teachers/examples	
“Benefit: This app gives the youth empowerment over their environment, while in a condition that would otherwise force them to rely on others. Developing this app, helped these two young innovators understand the impact that their creations can have on the lives of others.”	
“Benefit: This app gives an individual more power over their environment, rather than having to rely on others. Developing this app helped these two young innovators measurably improve the lives of others.”																						
- [x] http://iot.appinventor.mit.edu/#/students/intro	
“You can choose from a wealth of sensors—for temperature, sound, light, color, moisture, motion, touch, heart rate and many others, with new sensors appearing daily.”	
Please replace with: “You can use sensors to capture a wealth of data, including temperature, sound, light, color, moisture, motion, touch, heart rate, and many more, with support for new sensors appearing daily.”	
																				
- [x] http://iot.appinventor.mit.edu/#/makers/intro	
“The things you make with MIT App Inventor IoT can read information from a panoply of sensors (temperature, moisture, voltage, pressure, noise, heart rate, chemicals, …) and control a host of devices (buttons, buzzers, lights, appliances, robots, …).”	
Please replace "things" with "apps."	
																					
- [x] http://iot.appinventor.mit.edu/#/makers/intro	
“Best of all, you can interface these IoT devices with App Inventor apps you create for your smartphone, and take advantage of all the features that App Inventor provides, including speech understanding, language translation and Web communication.”	
Please change to: “Best of all, you can run these apps from your smartphone, and take advantage of all the features that App Inventor provides, including speech understanding, language translation and Web communication.”																						
- [x] http://iot.appinventor.mit.edu/#/help/intro	“We have a bunch in the tutorials section, but we suggest starting with the Light Sensor and RGB LCD Display tutorials”	
Please replace with: "We suggest starting with the Light Sensor and RGB LCD Display tutorials, then exploring on your own!" 
																						
Thank you so much!
-Hedge

**Comment by marksherman** [comment]
assign to me

**Comment by farxinu** [comment]
The Getting Started page refers to the Arduino 101 and the grove shield but not the micro:bit.

**Comment by marksherman** [comment]
@farxinu please break out into a new issue or add to an existing issue about incomplete content. This change will only reflect these approved edits.
