### ISSUE TITLE
Tutorials and HowTos should have URLs

### ISSUE THREAD

**Issue by marksherman** [mit-cml/iot-website-source#64]
su @halatmit 
I was looking at the IoT site and the (still to be finished) pages of tutorials and howTos.  As far as I can see, the individual PDFs on the pages do not have specific URLs -- or at least it wasn't obvious to me.  Please fix.  

(@afmckinney @ewpatton)

**Comment by ewpatton** [comment]
This was resolved by email. Site users can right-click on the tutorial and how to links and select the browser's "Copy Link Address" menu item to get the URL for the PDF. Adding an additional field with the URL explicitly stated may make the page too busy.
